backend:
  name: github
  repo: https://github.com/JoshLong23/barebones-NetlifyCMS

media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: path, label: Path }
      - { name: body, label: Body, widget: markdown }
